package example

// Code generated by surrealtag; DO NOT EDIT.
type recordJSON struct {
	ID          idJSON     `json:"id"`
	RequestedAt strandJSON `json:"requested_at"`
	RespondedAt strandJSON `json:"responded_at"`
}
type strandJSON struct {
	Strand string `json:"Strand"`
}

func fromrecordJSON(j recordJSON) Record {
	s := Record{}
	s.ID.ID = j.ID.Inner.Inner.ID.String
	s.ID.TB = j.ID.Inner.Inner.TB
	s.RequestedAt = j.RequestedAt.Strand
	s.RespondedAt = j.RespondedAt.Strand
	return s
}

type objectJSON struct {
	Inner recordJSON `json:"Object"`
}
type arrayJSON struct {
	Inner []objectJSON `json:"Array"`
}
type idJSON struct {
	Inner innerIDJSON `json:"id"`
}
type innerIDJSON struct {
	Inner innerInnerIDJSON `json:"Thing"`
}
type innerInnerIDJSON struct {
	ID idStringJSON `json:"id"`
	TB string       `json:"tb"`
}
type idStringJSON struct {
	String string `json:"String"`
}
