package main

// Code generated by surrealtag; DO NOT EDIT.
type recordJSON struct {
	RequestedAt strandJSON `json:"requested_at"`
	RespondedAt strandJSON `json:"responded_at"`
}
type strandJSON struct {
	Strand string `json:"Strand"`
}

func fromrecordJSON(j recordJSON) Record {
	s := Record{}
	s.RequestedAt = j.RequestedAt.Strand
	s.RespondedAt = j.RespondedAt.Strand
	return s
}

type objectJSON struct {
	Inner recordJSON `json:"Object"`
}
type arrayJSON struct {
	Inner []objectJSON `json:"Array"`
}
